//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LibraryModel", "FK__tbl_issue__BookI__15502E78", "tbl_book", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LibraryManagementSystem.tbl_book), "tbl_issue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LibraryManagementSystem.tbl_issue), true)]
[assembly: EdmRelationshipAttribute("LibraryModel", "FK_tbl_request_tbl_request", "tbl_student", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LibraryManagementSystem.tbl_student), "tbl_request", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LibraryManagementSystem.tbl_request), true)]
[assembly: EdmRelationshipAttribute("LibraryModel", "FK__tbl_issue__Stude__164452B1", "tbl_student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LibraryManagementSystem.tbl_student), "tbl_issue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LibraryManagementSystem.tbl_issue), true)]
[assembly: EdmRelationshipAttribute("LibraryModel", "FK_tbl_studentLogin_tbl_student", "tbl_student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LibraryManagementSystem.tbl_student), "tbl_studentLogin", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LibraryManagementSystem.tbl_studentLogin), true)]
[assembly: EdmRelationshipAttribute("LibraryModel", "FK__tbl_teach__Login__267ABA7A", "tbl_teacher", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LibraryManagementSystem.tbl_teacher), "tbl_teacherLogin", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LibraryManagementSystem.tbl_teacherLogin), true)]

#endregion

namespace LibraryManagementSystem
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LibraryDBContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LibraryDBContext object using the connection string found in the 'LibraryDBContext' section of the application configuration file.
        /// </summary>
        public LibraryDBContext() : base("name=LibraryDBContext", "LibraryDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LibraryDBContext object.
        /// </summary>
        public LibraryDBContext(string connectionString) : base(connectionString, "LibraryDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LibraryDBContext object.
        /// </summary>
        public LibraryDBContext(EntityConnection connection) : base(connection, "LibraryDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_book> tbl_book
        {
            get
            {
                if ((_tbl_book == null))
                {
                    _tbl_book = base.CreateObjectSet<tbl_book>("tbl_book");
                }
                return _tbl_book;
            }
        }
        private ObjectSet<tbl_book> _tbl_book;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_request> tbl_request
        {
            get
            {
                if ((_tbl_request == null))
                {
                    _tbl_request = base.CreateObjectSet<tbl_request>("tbl_request");
                }
                return _tbl_request;
            }
        }
        private ObjectSet<tbl_request> _tbl_request;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_student> tbl_student
        {
            get
            {
                if ((_tbl_student == null))
                {
                    _tbl_student = base.CreateObjectSet<tbl_student>("tbl_student");
                }
                return _tbl_student;
            }
        }
        private ObjectSet<tbl_student> _tbl_student;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_teacher> tbl_teacher
        {
            get
            {
                if ((_tbl_teacher == null))
                {
                    _tbl_teacher = base.CreateObjectSet<tbl_teacher>("tbl_teacher");
                }
                return _tbl_teacher;
            }
        }
        private ObjectSet<tbl_teacher> _tbl_teacher;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_issue> tbl_issue
        {
            get
            {
                if ((_tbl_issue == null))
                {
                    _tbl_issue = base.CreateObjectSet<tbl_issue>("tbl_issue");
                }
                return _tbl_issue;
            }
        }
        private ObjectSet<tbl_issue> _tbl_issue;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_studentLogin> tbl_studentLogin
        {
            get
            {
                if ((_tbl_studentLogin == null))
                {
                    _tbl_studentLogin = base.CreateObjectSet<tbl_studentLogin>("tbl_studentLogin");
                }
                return _tbl_studentLogin;
            }
        }
        private ObjectSet<tbl_studentLogin> _tbl_studentLogin;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_teacherLogin> tbl_teacherLogin
        {
            get
            {
                if ((_tbl_teacherLogin == null))
                {
                    _tbl_teacherLogin = base.CreateObjectSet<tbl_teacherLogin>("tbl_teacherLogin");
                }
                return _tbl_teacherLogin;
            }
        }
        private ObjectSet<tbl_teacherLogin> _tbl_teacherLogin;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_book EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_book(tbl_book tbl_book)
        {
            base.AddObject("tbl_book", tbl_book);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_request EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_request(tbl_request tbl_request)
        {
            base.AddObject("tbl_request", tbl_request);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_student EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_student(tbl_student tbl_student)
        {
            base.AddObject("tbl_student", tbl_student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_teacher EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_teacher(tbl_teacher tbl_teacher)
        {
            base.AddObject("tbl_teacher", tbl_teacher);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_issue EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_issue(tbl_issue tbl_issue)
        {
            base.AddObject("tbl_issue", tbl_issue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_studentLogin EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_studentLogin(tbl_studentLogin tbl_studentLogin)
        {
            base.AddObject("tbl_studentLogin", tbl_studentLogin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_teacherLogin EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_teacherLogin(tbl_teacherLogin tbl_teacherLogin)
        {
            base.AddObject("tbl_teacherLogin", tbl_teacherLogin);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="tbl_book")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_book : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_book object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        public static tbl_book Createtbl_book(global::System.Int32 code)
        {
            tbl_book tbl_book = new tbl_book();
            tbl_book.Code = code;
            return tbl_book;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, "Code");
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.Int32 _Code;
        partial void OnCodeChanging(global::System.Int32 value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BookName
        {
            get
            {
                return _BookName;
            }
            set
            {
                OnBookNameChanging(value);
                ReportPropertyChanging("BookName");
                _BookName = StructuralObject.SetValidValue(value, true, "BookName");
                ReportPropertyChanged("BookName");
                OnBookNameChanged();
            }
        }
        private global::System.String _BookName;
        partial void OnBookNameChanging(global::System.String value);
        partial void OnBookNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true, "Author");
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Publication
        {
            get
            {
                return _Publication;
            }
            set
            {
                OnPublicationChanging(value);
                ReportPropertyChanging("Publication");
                _Publication = StructuralObject.SetValidValue(value, true, "Publication");
                ReportPropertyChanged("Publication");
                OnPublicationChanged();
            }
        }
        private global::System.String _Publication;
        partial void OnPublicationChanging(global::System.String value);
        partial void OnPublicationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true, "Subject");
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NoOfCopies
        {
            get
            {
                return _NoOfCopies;
            }
            set
            {
                OnNoOfCopiesChanging(value);
                ReportPropertyChanging("NoOfCopies");
                _NoOfCopies = StructuralObject.SetValidValue(value, "NoOfCopies");
                ReportPropertyChanged("NoOfCopies");
                OnNoOfCopiesChanged();
            }
        }
        private Nullable<global::System.Int32> _NoOfCopies;
        partial void OnNoOfCopiesChanging(Nullable<global::System.Int32> value);
        partial void OnNoOfCopiesChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "FK__tbl_issue__BookI__15502E78", "tbl_issue")]
        public EntityCollection<tbl_issue> tbl_issue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_issue>("LibraryModel.FK__tbl_issue__BookI__15502E78", "tbl_issue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_issue>("LibraryModel.FK__tbl_issue__BookI__15502E78", "tbl_issue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="tbl_issue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_issue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_issue object.
        /// </summary>
        /// <param name="bookId">Initial value of the BookId property.</param>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        public static tbl_issue Createtbl_issue(global::System.Int32 bookId, global::System.Int32 studentId)
        {
            tbl_issue tbl_issue = new tbl_issue();
            tbl_issue.BookId = bookId;
            tbl_issue.StudentId = studentId;
            return tbl_issue;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookId
        {
            get
            {
                return _BookId;
            }
            set
            {
                if (_BookId != value)
                {
                    OnBookIdChanging(value);
                    ReportPropertyChanging("BookId");
                    _BookId = StructuralObject.SetValidValue(value, "BookId");
                    ReportPropertyChanged("BookId");
                    OnBookIdChanged();
                }
            }
        }
        private global::System.Int32 _BookId;
        partial void OnBookIdChanging(global::System.Int32 value);
        partial void OnBookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                if (_StudentId != value)
                {
                    OnStudentIdChanging(value);
                    ReportPropertyChanging("StudentId");
                    _StudentId = StructuralObject.SetValidValue(value, "StudentId");
                    ReportPropertyChanged("StudentId");
                    OnStudentIdChanged();
                }
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IssueDate
        {
            get
            {
                return _IssueDate;
            }
            set
            {
                OnIssueDateChanging(value);
                ReportPropertyChanging("IssueDate");
                _IssueDate = StructuralObject.SetValidValue(value, "IssueDate");
                ReportPropertyChanged("IssueDate");
                OnIssueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _IssueDate;
        partial void OnIssueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnIssueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReturnDate
        {
            get
            {
                return _ReturnDate;
            }
            set
            {
                OnReturnDateChanging(value);
                ReportPropertyChanging("ReturnDate");
                _ReturnDate = StructuralObject.SetValidValue(value, "ReturnDate");
                ReportPropertyChanged("ReturnDate");
                OnReturnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReturnDate;
        partial void OnReturnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnReturnDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "FK__tbl_issue__BookI__15502E78", "tbl_book")]
        public tbl_book tbl_book
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_book>("LibraryModel.FK__tbl_issue__BookI__15502E78", "tbl_book").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_book>("LibraryModel.FK__tbl_issue__BookI__15502E78", "tbl_book").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_book> tbl_bookReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_book>("LibraryModel.FK__tbl_issue__BookI__15502E78", "tbl_book");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_book>("LibraryModel.FK__tbl_issue__BookI__15502E78", "tbl_book", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "FK__tbl_issue__Stude__164452B1", "tbl_student")]
        public tbl_student tbl_student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("LibraryModel.FK__tbl_issue__Stude__164452B1", "tbl_student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("LibraryModel.FK__tbl_issue__Stude__164452B1", "tbl_student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_student> tbl_studentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("LibraryModel.FK__tbl_issue__Stude__164452B1", "tbl_student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_student>("LibraryModel.FK__tbl_issue__Stude__164452B1", "tbl_student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="tbl_request")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_request : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_request object.
        /// </summary>
        /// <param name="requestId">Initial value of the RequestId property.</param>
        public static tbl_request Createtbl_request(global::System.Int32 requestId)
        {
            tbl_request tbl_request = new tbl_request();
            tbl_request.RequestId = requestId;
            return tbl_request;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestId
        {
            get
            {
                return _RequestId;
            }
            set
            {
                if (_RequestId != value)
                {
                    OnRequestIdChanging(value);
                    ReportPropertyChanging("RequestId");
                    _RequestId = StructuralObject.SetValidValue(value, "RequestId");
                    ReportPropertyChanged("RequestId");
                    OnRequestIdChanged();
                }
            }
        }
        private global::System.Int32 _RequestId;
        partial void OnRequestIdChanging(global::System.Int32 value);
        partial void OnRequestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BookName
        {
            get
            {
                return _BookName;
            }
            set
            {
                OnBookNameChanging(value);
                ReportPropertyChanging("BookName");
                _BookName = StructuralObject.SetValidValue(value, true, "BookName");
                ReportPropertyChanged("BookName");
                OnBookNameChanged();
            }
        }
        private global::System.String _BookName;
        partial void OnBookNameChanging(global::System.String value);
        partial void OnBookNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true, "Author");
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true, "Subject");
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                OnStudentIdChanging(value);
                ReportPropertyChanging("StudentId");
                _StudentId = StructuralObject.SetValidValue(value, "StudentId");
                ReportPropertyChanged("StudentId");
                OnStudentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _StudentId;
        partial void OnStudentIdChanging(Nullable<global::System.Int32> value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "FK_tbl_request_tbl_request", "tbl_student")]
        public tbl_student tbl_student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("LibraryModel.FK_tbl_request_tbl_request", "tbl_student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("LibraryModel.FK_tbl_request_tbl_request", "tbl_student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_student> tbl_studentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("LibraryModel.FK_tbl_request_tbl_request", "tbl_student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_student>("LibraryModel.FK_tbl_request_tbl_request", "tbl_student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="tbl_student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_student object.
        /// </summary>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        public static tbl_student Createtbl_student(global::System.Int32 studentId)
        {
            tbl_student tbl_student = new tbl_student();
            tbl_student.StudentId = studentId;
            return tbl_student;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                if (_StudentId != value)
                {
                    OnStudentIdChanging(value);
                    ReportPropertyChanging("StudentId");
                    _StudentId = StructuralObject.SetValidValue(value, "StudentId");
                    ReportPropertyChanged("StudentId");
                    OnStudentIdChanged();
                }
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentName
        {
            get
            {
                return _StudentName;
            }
            set
            {
                OnStudentNameChanging(value);
                ReportPropertyChanging("StudentName");
                _StudentName = StructuralObject.SetValidValue(value, true, "StudentName");
                ReportPropertyChanged("StudentName");
                OnStudentNameChanged();
            }
        }
        private global::System.String _StudentName;
        partial void OnStudentNameChanging(global::System.String value);
        partial void OnStudentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RegNo
        {
            get
            {
                return _RegNo;
            }
            set
            {
                OnRegNoChanging(value);
                ReportPropertyChanging("RegNo");
                _RegNo = StructuralObject.SetValidValue(value, "RegNo");
                ReportPropertyChanged("RegNo");
                OnRegNoChanged();
            }
        }
        private Nullable<global::System.Int32> _RegNo;
        partial void OnRegNoChanging(Nullable<global::System.Int32> value);
        partial void OnRegNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String branch
        {
            get
            {
                return _branch;
            }
            set
            {
                OnbranchChanging(value);
                ReportPropertyChanging("branch");
                _branch = StructuralObject.SetValidValue(value, true, "branch");
                ReportPropertyChanged("branch");
                OnbranchChanged();
            }
        }
        private global::System.String _branch;
        partial void OnbranchChanging(global::System.String value);
        partial void OnbranchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Section
        {
            get
            {
                return _Section;
            }
            set
            {
                OnSectionChanging(value);
                ReportPropertyChanging("Section");
                _Section = StructuralObject.SetValidValue(value, true, "Section");
                ReportPropertyChanged("Section");
                OnSectionChanged();
            }
        }
        private global::System.String _Section;
        partial void OnSectionChanging(global::System.String value);
        partial void OnSectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Semester
        {
            get
            {
                return _Semester;
            }
            set
            {
                OnSemesterChanging(value);
                ReportPropertyChanging("Semester");
                _Semester = StructuralObject.SetValidValue(value, true, "Semester");
                ReportPropertyChanged("Semester");
                OnSemesterChanged();
            }
        }
        private global::System.String _Semester;
        partial void OnSemesterChanging(global::System.String value);
        partial void OnSemesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> YearOfAdmission
        {
            get
            {
                return _YearOfAdmission;
            }
            set
            {
                OnYearOfAdmissionChanging(value);
                ReportPropertyChanging("YearOfAdmission");
                _YearOfAdmission = StructuralObject.SetValidValue(value, "YearOfAdmission");
                ReportPropertyChanged("YearOfAdmission");
                OnYearOfAdmissionChanged();
            }
        }
        private Nullable<global::System.Int32> _YearOfAdmission;
        partial void OnYearOfAdmissionChanging(Nullable<global::System.Int32> value);
        partial void OnYearOfAdmissionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "FK_tbl_request_tbl_request", "tbl_request")]
        public EntityCollection<tbl_request> tbl_request
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_request>("LibraryModel.FK_tbl_request_tbl_request", "tbl_request");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_request>("LibraryModel.FK_tbl_request_tbl_request", "tbl_request", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "FK__tbl_issue__Stude__164452B1", "tbl_issue")]
        public EntityCollection<tbl_issue> tbl_issue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_issue>("LibraryModel.FK__tbl_issue__Stude__164452B1", "tbl_issue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_issue>("LibraryModel.FK__tbl_issue__Stude__164452B1", "tbl_issue", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "FK_tbl_studentLogin_tbl_student", "tbl_studentLogin")]
        public tbl_studentLogin tbl_studentLogin
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_studentLogin>("LibraryModel.FK_tbl_studentLogin_tbl_student", "tbl_studentLogin").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_studentLogin>("LibraryModel.FK_tbl_studentLogin_tbl_student", "tbl_studentLogin").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_studentLogin> tbl_studentLoginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_studentLogin>("LibraryModel.FK_tbl_studentLogin_tbl_student", "tbl_studentLogin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_studentLogin>("LibraryModel.FK_tbl_studentLogin_tbl_student", "tbl_studentLogin", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="tbl_studentLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_studentLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_studentLogin object.
        /// </summary>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        public static tbl_studentLogin Createtbl_studentLogin(global::System.Int32 studentId)
        {
            tbl_studentLogin tbl_studentLogin = new tbl_studentLogin();
            tbl_studentLogin.StudentId = studentId;
            return tbl_studentLogin;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                if (_StudentId != value)
                {
                    OnStudentIdChanging(value);
                    ReportPropertyChanging("StudentId");
                    _StudentId = StructuralObject.SetValidValue(value, "StudentId");
                    ReportPropertyChanged("StudentId");
                    OnStudentIdChanged();
                }
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "FK_tbl_studentLogin_tbl_student", "tbl_student")]
        public tbl_student tbl_student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("LibraryModel.FK_tbl_studentLogin_tbl_student", "tbl_student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("LibraryModel.FK_tbl_studentLogin_tbl_student", "tbl_student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_student> tbl_studentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_student>("LibraryModel.FK_tbl_studentLogin_tbl_student", "tbl_student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_student>("LibraryModel.FK_tbl_studentLogin_tbl_student", "tbl_student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="tbl_teacher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_teacher : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_teacher object.
        /// </summary>
        /// <param name="teacherId">Initial value of the TeacherId property.</param>
        public static tbl_teacher Createtbl_teacher(global::System.Int32 teacherId)
        {
            tbl_teacher tbl_teacher = new tbl_teacher();
            tbl_teacher.TeacherId = teacherId;
            return tbl_teacher;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeacherId
        {
            get
            {
                return _TeacherId;
            }
            set
            {
                if (_TeacherId != value)
                {
                    OnTeacherIdChanging(value);
                    ReportPropertyChanging("TeacherId");
                    _TeacherId = StructuralObject.SetValidValue(value, "TeacherId");
                    ReportPropertyChanged("TeacherId");
                    OnTeacherIdChanged();
                }
            }
        }
        private global::System.Int32 _TeacherId;
        partial void OnTeacherIdChanging(global::System.Int32 value);
        partial void OnTeacherIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Designation
        {
            get
            {
                return _Designation;
            }
            set
            {
                OnDesignationChanging(value);
                ReportPropertyChanging("Designation");
                _Designation = StructuralObject.SetValidValue(value, true, "Designation");
                ReportPropertyChanged("Designation");
                OnDesignationChanged();
            }
        }
        private global::System.String _Designation;
        partial void OnDesignationChanging(global::System.String value);
        partial void OnDesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Branch
        {
            get
            {
                return _Branch;
            }
            set
            {
                OnBranchChanging(value);
                ReportPropertyChanging("Branch");
                _Branch = StructuralObject.SetValidValue(value, true, "Branch");
                ReportPropertyChanged("Branch");
                OnBranchChanged();
            }
        }
        private global::System.String _Branch;
        partial void OnBranchChanging(global::System.String value);
        partial void OnBranchChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ContactNumber
        {
            get
            {
                return _ContactNumber;
            }
            set
            {
                OnContactNumberChanging(value);
                ReportPropertyChanging("ContactNumber");
                _ContactNumber = StructuralObject.SetValidValue(value, "ContactNumber");
                ReportPropertyChanged("ContactNumber");
                OnContactNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _ContactNumber;
        partial void OnContactNumberChanging(Nullable<global::System.Int32> value);
        partial void OnContactNumberChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "FK__tbl_teach__Login__267ABA7A", "tbl_teacherLogin")]
        public tbl_teacherLogin tbl_teacherLogin
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_teacherLogin>("LibraryModel.FK__tbl_teach__Login__267ABA7A", "tbl_teacherLogin").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_teacherLogin>("LibraryModel.FK__tbl_teach__Login__267ABA7A", "tbl_teacherLogin").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_teacherLogin> tbl_teacherLoginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_teacherLogin>("LibraryModel.FK__tbl_teach__Login__267ABA7A", "tbl_teacherLogin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_teacherLogin>("LibraryModel.FK__tbl_teach__Login__267ABA7A", "tbl_teacherLogin", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LibraryModel", Name="tbl_teacherLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_teacherLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_teacherLogin object.
        /// </summary>
        /// <param name="teacherId">Initial value of the TeacherId property.</param>
        public static tbl_teacherLogin Createtbl_teacherLogin(global::System.Int32 teacherId)
        {
            tbl_teacherLogin tbl_teacherLogin = new tbl_teacherLogin();
            tbl_teacherLogin.TeacherId = teacherId;
            return tbl_teacherLogin;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeacherId
        {
            get
            {
                return _TeacherId;
            }
            set
            {
                if (_TeacherId != value)
                {
                    OnTeacherIdChanging(value);
                    ReportPropertyChanging("TeacherId");
                    _TeacherId = StructuralObject.SetValidValue(value, "TeacherId");
                    ReportPropertyChanged("TeacherId");
                    OnTeacherIdChanged();
                }
            }
        }
        private global::System.Int32 _TeacherId;
        partial void OnTeacherIdChanging(global::System.Int32 value);
        partial void OnTeacherIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true, "UserName");
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LibraryModel", "FK__tbl_teach__Login__267ABA7A", "tbl_teacher")]
        public tbl_teacher tbl_teacher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_teacher>("LibraryModel.FK__tbl_teach__Login__267ABA7A", "tbl_teacher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_teacher>("LibraryModel.FK__tbl_teach__Login__267ABA7A", "tbl_teacher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_teacher> tbl_teacherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_teacher>("LibraryModel.FK__tbl_teach__Login__267ABA7A", "tbl_teacher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_teacher>("LibraryModel.FK__tbl_teach__Login__267ABA7A", "tbl_teacher", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
